### ISSUE TITLE
0.5.0 Release Checklist

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli-deploy#271]
## Now

Update to ember-cli-deploy-plugin 0.2.0 (including updating `this.log` calls) and release non-beta version of these plugins:

- [x] ember-cli-deploy-ssh-tunnel 
- [ ] ember-cli-deploy-cp
- [x] [ember-cli-deploy-git-tag](https://github.com/minutebase/ember-cli-deploy-git-tag)
- [x] ember-cli-deploy-notify-firebase
- [x] ember-cli-deploy-sentry
- [x] ember-cli-deploy-azure-blob
- [x] ember-cli-deploy-azure-tables

## Release Day

- [x] Tag 0.5.0
- [x] Changelog
- [x] Release Notes
- [x] Update docs so 0.5.0 are default docs
- [x] Publish to npm
- [x] Announce in a fun way at a conference 
- [x] Tweet

**Comment by duizendnegen** [comment]
won't 0.5.0 be tagged (silently) so I can base my release pack on this too?

**Comment by duizendnegen** [comment]
updating & publishing azure-blob & azure-tables is done, will also amend the docs to feature the plugin pack (which is also now released)

**Comment by lukemelia** [comment]
https://i.imgflip.com/tdfom.jpg

**Comment by ghedamat** [comment]
:+1:
